### PR TITLE
Add test for large heap that pushes the limits

### PR DESCRIPTION
**Pull request by zburk**
Issue #14. Makes sure that your methods don't address elements outside of the array size

I'm doing more testing on my implementation to make sure it's all good so if I develop a test, might as well submit it.

### CODE REVIEW

**Comment by heyTruth** [comment]
I got an index out of bound error for line 455 heap.delMin().

**Comment by zburk** [comment]
That's the point of the test. You need to make sure that your methods don't refer to elements that are beyond the array size. [Piazza](https://piazza.com/class/ixgyq2l7r9s8x?cid=104)

If you check your code and something is wrong with the test, let me know though. It passes for me though and I had to add bounds checks for my code

**Comment by heyTruth** [comment]
But I got everything right for the oracle tests. Emmmm that is weird. It says that the error occurs in my delete method. My delete method uses a while loop to make sure that the left child (pointer * 2) of the current pointer is not null. Could that be the reason I got the error?

**Comment by zburk** [comment]
Yeah I was passing the oracle tests too but those don't check all possible things that could happen.

I'm not sure whether or not I can say anything without violating the Honor Code. I'd say if you think that's a potential issue, then to try and add a bounds check and see if it passes the test

**Comment by heyTruth** [comment]
Sure. I will try to add bounds checks. Thanks!

**Pull request merged**
